### ISSUE TITLE
Builds failing.

### ISSUE THREAD

**Issue by ancker010** [neggles/sd-webui-docker#4]
These have been failing for quite a while now.
Just curious if you're still planning on maintaining them.

**Comment by neggles** [comment]
Yeaaaaaaaah, I *do* plan on fixing these but I've been really busy lately with training some things, and I was hoping to convert everything over to using my new NGC base container. Will try to get to this in the next couple days, sorry for the meantime!

**Comment by neggles** [comment]
I'm working on these right now, and should have them working shortly, FWIW. Vlad image seems to already be fixed but I haven't tested, new auto build is running. 

(I finally got around to needing to update my own container, I've just been running on 1.4.2 heh)
