### ISSUE TITLE
Project is DEAD

### ISSUE THREAD

**Issue by F1zzyD** [neggles/sd-webui-docker#8]
Getting error SD_WEEBUI_VARIANT: unbound variable while running the docker-compose.yml. The wiki leads no where. I'm assuming this project is dead then. Please take it down.

**Comment by neggles** [comment]
Way to jump to conclusions. No, it's not dead, you could try reading the docs or learning a thing or two about how docker-compose works and figuring it out for yourself - or failing that, at least asking nicely for help. Go away.

**Comment by rom4ster** [comment]
There are 2 comments here, both of them useless. 

Can we not ask for projects to be taken down 
and
Can we actually get a solution for this? 

Im running into the same thing and its extremely frustrating to see this useless way of asking for help and the useless answer

**Comment by xxcomcadxx** [comment]
replace your docker-compose.yml with the below... thank chatgpt and 4 hours of troubleshooting on my end


version: "3.7"

services:
  webui:
    image: ghcr.io/neggles/sd-webui-docker:latest
    restart: unless-stopped
    container_name: sd-webui
    build:
      context: ./docker
      dockerfile: Dockerfile
      target: webui
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      CLI_ARGS: "--skip-version-check --allow-code --enable-insecure-extension-access --api --xformers --opt-chan>      PYTHONUNBUFFERED: "1"
      TERM: "${TERM}"
      SD_WEBUI_VARIANT: "default"  # <-- added this variable
    ports:
      - mode: ingress
        target: 7860
        published: 7860
        protocol: tcp
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./output
        target: /output

  browser:
    image: ghcr.io/neggles/sd-webui-docker/browser:latest
    restart: unless-stopped
    container_name: sd-browser
    profiles:
      - "browser"  # <-- fixed the indentation
    build:
      context: ./browser
      dockerfile: Dockerfile
      target: browser
    environment:
      BROWSER_PORT: 7869
    ports:
      - mode: ingress
        target: 7869
        published: 7869
        protocol: tcp
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./output
        target: /output
